port @REDIS_PORT@
protected-mode no
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-announce-ip @CLUSTER_ANNOUNCE_IP@
cluster-announce-port @REDIS_PORT@
appendonly yes
pidfile /var/run/redis.pid
masterauth abc123
requirepass abc123
