# dockerized virtual environment
version: '3.9'

services:

  redis-standalone:
    image: redis:6.2.1-alpine
    restart: always
    entrypoint: [redis-server, /etc/redis/redis.conf]
    healthcheck:
      test: "redis-cli -p 6479 info"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./.state/redis-standalone/conf/:/etc/redis/
      - ./.state/redis-standalone/data/:/data
    ports:
      - "6479:6479"
